# Generated by Django 4.1.7 on 2023-03-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiztype',
            options={'verbose_name': 'QuizType', 'verbose_name_plural': 'QuizTypes'},
        ),
    ]
